### PR TITLE
Doesn't work on a white terminal

### PR DESCRIPTION
**Pull request by jrf0110**
The default Terminal in the Mac OS is black text on a white background. `ngh --help` works, but `ngh issues` outputs a black background, so the black text can't be read.

### CODE REVIEW

**Comment by jrf0110** [comment]
riiiiiight specifying the color for that text will solve the issue. I'll check it out later today

**Comment by ljharb** [comment]
Thanks! It would also be nice if it matched the window's existing color scheme, but I don't know if that's possible.

If `ngh` is going to decide the color, it would be nice if all of its output (not just the issue list) followed the same color scheme (right now it's inconsistent)

**Comment by jrf0110** [comment]
Yeah, I feel bad for hijacking the scheme (or rather making the assumption that other users will be on a similar color scheme).

A quick and dirty solution would be to do like I said in my previous comment. However, that _feels  wrong_. A better solution would be for ngh to make less color scheme assumptions, and provide a mechanism for using different templates for output.

```
ngh issues --format table
ngh issues --format striped-table
ngh issues --format json | json-beautify > issues.json
```

**Comment by jrf0110** [comment]
okie doke. I started the initial work to properly separate my CLI command controllers from the views themselves. This will allow for a plugin-able view architecture where I could see you doing something like this in the future:

**Configure NGH to use a certain format by default for issues**

```
-- built-in tmpl
ngh configure issues --format striped-table
-- some npm installed template module
ngh configure issues --format peer-dependent-issues-tmpl-module
-- or a path to the module
ngh configure issues --format /path-to/my-issues-tmpl-module
```

I think that would be the best solution since it would be a pain and totally unreliable to try and figure out the current term color scheme.

**Comment by jrf0110** [comment]
@ljharb I'm going to review this PR in the morning to make sure I didn't mess anything up :) Should be good to go and distributed as `v0.2.11` by tomorrow afternoon

**Comment by ljharb** [comment]
Sounds great, thanks!

**Pull request merged**
